language: cpp
os: linux
compiler: clang

cache: # see https://docs.travis-ci.com/user/caching/
- directories:
  - $HOME/.cache

addons:
  apt:
    packages:
    - clang
    - llvm
    - binutils

install:
# (fake) install dependencies (usually involves wget, configure, make, ...)
# install into cache folder (build binaries+headers only, no sources and do NOT build there)
- mkdir -p $HOME/.cache
- touch $HOME/.cache/mydependency.so

script: ./build.sh

after_success:
# Create lcov report
# capture coverage info
- llvm-profdata merge -o $HOME/profile.profdata -sparse $HOME/profiles/
# filter out system and extra files.
# To also not include test code in coverage add them with full path to the patterns: '*/tests/*'
- ls -lR
- llvm-cov show -Xdemangler c++filt -instr-profile=$HOME/profile.profdata ./build/tests/tests > coverage.info
# Uploading to CodeCov
# '-f' specifies file(s) to use and disables manual coverage gathering and file search which has already been done above
- bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"
